"""Generate and execution-verify reference solutions for LiveCodeBench.

    python -m harness.solve_lcb --versions v6 --attempts 3

LCB ships no ground-truth code, and the study needs known-correct code to use
as a baseline and to mutate. Solutions are generated by a model and kept only if
they pass every public and private test, verified by execution, so a wrong
solution cannot silently become the reference.

These references are model-authored, unlike HumanEval's human-written canonical
solutions, which is arguably closer to the deployed setting where judges review
model-written code. If the generator is also a judge there is a self-preference
concern, largely defused by the design: every reported quantity is a paired
delta against the problem's own baseline, so authorship is common to both sides
of the subtraction. Set --model to a non-judge model to remove it entirely.

Output: data/lcb_solutions.jsonl  {task_id, code, verified, attempts, ...}
"""

from __future__ import annotations

import argparse
import hashlib
import json
from concurrent.futures import ThreadPoolExecutor, as_completed

from . import config, livecodebench, oracle, providers

SYSTEM = (
    "You are a competitive programmer. You write correct, complete Python "
    "solutions that handle every stated constraint and edge case."
)

USER = """\
Solve the following problem in Python.

{statement}

Complete this exact signature (keep the class and method names unchanged):

```python
{starter}
```

Return the complete solution: the full `class Solution` with the method \
implemented. Assume `typing`, `collections`, `math`, `heapq`, `bisect`, \
`itertools` and `functools` are already imported. Do not include a docstring, \
example usage, tests, or explanatory prose."""

SCHEMA = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": "The complete `class Solution` definition. Python source only.",
        }
    },
    "required": ["code"],
    "additionalProperties": False,
}


def verify(code: str, entry_point: str, inputs: list, expected: list) -> bool:
    """Run the candidate against LCB's own expected outputs, compared through
    the oracle's canonicaliser so float formatting, tuple-vs-list and set
    ordering are handled as they are everywhere else."""
    res = oracle._run(livecodebench.PREAMBLE + code, entry_point, inputs,
                      timeout=config.EXEC_TIMEOUT_S * 2)
    if "results" not in res:
        return False
    return res["results"] == [oracle.canon(e) for e in expected]


class Solver:
    def __init__(self, spec_name: str, attempts: int):
        self.spec = config.SPECS[spec_name]
        self.provider = providers.build(self.spec)
        self.attempts = attempts

    def _generate(self, prob: dict, attempt: int) -> str | None:
        digest = hashlib.sha256(
            json.dumps({"task": prob["task_id"], "model": self.spec.model,
                        "provider": self.spec.provider, "attempt": attempt,
                        "temperature": [0.0, 0.4, 0.8][min(attempt, 2)]},
                       sort_keys=True).encode()
        ).hexdigest()
        path = config.CACHE / f"lcbsol-{digest}.json"
        cached = config.cache_read(path) if path.exists() else None
        if cached is not None:
            return cached.get("code")

        # Retries must differ: at temperature 0 every attempt returns the same
        # solution. Temperature climbs with the attempt index, and Claude specs
        # ignore it and vary by sampling instead.
        out = self.provider.complete(
            system=SYSTEM,
            user=USER.format(statement=prob["question_content"],
                             starter=prob["starter_code"].rstrip()),
            schema=SCHEMA,
            max_tokens=8192,
            thinking="adaptive",
            effort="high",
            temperature=[0.0, 0.4, 0.8][min(attempt, 2)],
        )
        code = out.data["code"] if out.data else None
        if out.error:
            print(f"  !! {prob['task_id']} attempt {attempt}: {out.error[:120]}")
        if code:                      # never cache a transient failure
            config.cache_write(path, {"code": code})
        return code

    def solve(self, prob: dict) -> dict:
        for attempt in range(self.attempts):
            code = self._generate(prob, attempt)
            if not code:
                continue
            try:
                if verify(code, prob["entry_point"], prob["inputs"], prob["expected"]):
                    return {"task_id": prob["task_id"], "code": code, "verified": True,
                            "attempts": attempt + 1, "difficulty": prob["difficulty"],
                            "contest_date": prob["contest_date"]}
            except Exception:
                continue
        return {"task_id": prob["task_id"], "code": None, "verified": False,
                "attempts": self.attempts, "difficulty": prob["difficulty"],
                "contest_date": prob["contest_date"]}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--versions", nargs="*", default=["v6"], choices=list(livecodebench.INCREMENTS))
    ap.add_argument("--since", default=None, help="ISO date lower bound on contest_date")
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--max-inputs", type=int, default=200)
    ap.add_argument("--attempts", type=int, default=3)
    ap.add_argument("--model", default=config.BUILDER,
                    help="a spec name from config.SPECS")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--out", default=str(config.DATA / "lcb_solutions.jsonl"))
    args = ap.parse_args()

    problems = livecodebench.load_raw(versions=args.versions, since=args.since,
                                      max_inputs=args.max_inputs)
    if args.limit:
        problems = problems[: args.limit]
    print(f"{len(problems)} functional LCB problems "
          f"({args.versions}, up to {args.attempts} attempts each, model={args.model})")

    solver = Solver(args.model, args.attempts)
    results: list[dict] = []
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures = [pool.submit(solver.solve, p) for p in problems]
        for i, fut in enumerate(as_completed(futures), start=1):
            results.append(fut.result())
            if i % 10 == 0 or i == len(problems):
                ok = sum(1 for r in results if r["verified"])
                print(f"  {i}/{len(problems)}  verified {ok}", flush=True)

    results.sort(key=lambda r: r["task_id"])
    with open(args.out, "w") as f:
        for r in results:
            f.write(json.dumps(r) + "\n")

    ok = [r for r in results if r["verified"]]
    print(f"\nverified {len(ok)}/{len(results)} -> {args.out}")
    by_diff: dict[str, list[int]] = {}
    for r in results:
        by_diff.setdefault(r["difficulty"], [0, 0])
        by_diff[r["difficulty"]][1] += 1
        by_diff[r["difficulty"]][0] += int(r["verified"])
    for d, (o, n) in sorted(by_diff.items()):
        print(f"  {d:8s} {o:3d}/{n:3d}")


if __name__ == "__main__":
    main()
